# This file is generated. Edit network-registry.yaml and rerun the generator.
# Registry: docs/reference/network-registry.yaml
# Site filter: reid

# irene-macbook alias
address=/irene-laptop/10.1.1.110
# irene-iphone alias
address=/irene-phone/10.1.1.105
# mudpi alias
address=/mudpi.vpn.home.arpa/10.8.1.1
# steven-iphone alias
address=/steven-phone/10.1.1.125
