# This file is generated. Edit network-registry.yaml and rerun the generator.
# Registry: docs/reference/network-registry.yaml
# Site filter: reid

ptr-record=1.1.1.10.in-addr.arpa,router.reid.home.arpa
ptr-record=105.1.1.10.in-addr.arpa,irene-iphone.reid.home.arpa
ptr-record=110.1.1.10.in-addr.arpa,irene-macbook.reid.home.arpa
ptr-record=125.1.1.10.in-addr.arpa,steven-iphone.reid.home.arpa
ptr-record=134.1.1.10.in-addr.arpa,stevenlaptop.reid.home.arpa
ptr-record=2.1.1.10.in-addr.arpa,vdsl-modem.reid.home.arpa
ptr-record=20.1.1.10.in-addr.arpa,shorepi.reid.home.arpa
ptr-record=3.1.1.10.in-addr.arpa,mudpi.reid.home.arpa
ptr-record=60.1.1.10.in-addr.arpa,printer.reid.home.arpa
