# This file is generated. Edit network-registry.yaml and rerun the generator.
# Registry: docs/reference/network-registry.yaml
# Site filter: reid
# Domain: reid.home.arpa

# printserver alias
address=/3dprintserver.reid.home.arpa/10.1.1.30
# cam-01 alias
address=/cam1.reid.home.arpa/10.1.1.41
# cam-02 alias
address=/cam2.reid.home.arpa/10.1.1.42
# cam-03 alias
address=/cam3.reid.home.arpa/10.1.1.43
# cam-04 alias
address=/cam4.reid.home.arpa/10.1.1.44
# cam-05 alias
address=/cam5.reid.home.arpa/10.1.1.45
# cam-06 alias
address=/cam6.reid.home.arpa/10.1.1.46
# cam-07 alias
address=/cam7.reid.home.arpa/10.1.1.47
# irene-macbook alias
address=/irene-laptop/10.1.1.110
# irene-iphone alias
address=/irene-phone/10.1.1.105
# mudpi alias
address=/mudpi.vpn.home.arpa/10.8.1.1
# shorepi alias
address=/signalk.reid.home.arpa/10.1.1.20
# steven-iphone alias
address=/steven-phone/10.1.1.125
