# Generated dnsmasq PTR records
# Source: docs/reference/network-registry.yaml

ptr-record=10.1.1.1,router.reid.home.arpa
ptr-record=10.1.1.6,abbhub.reid.home.arpa
ptr-record=10.1.1.10,mudpi.reid.home.arpa
ptr-record=10.1.1.20,shorepi.reid.home.arpa
ptr-record=10.1.1.30,printserver.reid.home.arpa
ptr-record=10.1.1.50,zappi.reid.home.arpa
ptr-record=10.8.1.1,mudpi.vpn.home.arpa
ptr-record=10.8.1.20,laptop.vpn.home.arpa
ptr-record=10.8.1.30,shedpi.vpn.home.arpa
ptr-record=10.8.1.40,boatdns.vpn.home.arpa
ptr-record=10.8.1.50,labdns.vpn.home.arpa
ptr-record=192.168.0.10,shedpi.barkingowl.home.arpa
ptr-record=192.168.0.50,weatherstation.barkingowl.home.arpa
ptr-record=192.168.97.10,labdns.testboat.home.arpa
ptr-record=192.168.98.10,boatdns.trilogy.home.arpa
ptr-record=192.168.98.20,signalk.trilogy.home.arpa
