[Interface]
PrivateKey = mKq7ioojuvm42LGruobQuDyVYsxHvcOx0niv2XzXNkk=
Address = 10.8.1.110/32
DNS = 10.1.1.3

[Peer]
PublicKey = uFNtaMvoLRCFYDu+Wbgj0XRa/5fRXPD8vaug8AiJIkE=
PresharedKey = CjgAxdET2RMI1cePfTxEydewwcQ1sxT2/yLNuZPHgIA=
Endpoint = mudpi.southsky.com.au:51820
AllowedIPs = 10.1.1.0/24, 192.168.0.0/24
PersistentKeepalive = 25
