# This file is generated. Edit network-registry.yaml and rerun the generator.
# Registry: docs/reference/network-registry.yaml
# Site filter: farm
# Domain: farm.home.arpa

# sunnyisland alias
address=/barkingisland/192.168.0.250
# sunnyboy1 alias
address=/barkingisland1/192.168.0.147
# sunnyboy2 alias
address=/barkingisland2/192.168.0.206
# sunnyboy3 alias
address=/barkingisland3/192.168.0.223
# shedpi alias
address=/shedpi/192.168.0.210
