\
#!/usr/bin/env python3
"""
generate-network-docs.py

Generate human-readable and dnsmasq-friendly artifacts from
docs/reference/network-registry.yaml.

Outputs into ./generated by default:

- generated/host-registry.md
- generated/site-summary.md
- generated/addressing-plan.md
- generated/network-inventory.md
- generated/validation.md
- generated/dnsmasq/hosts.conf
- generated/dnsmasq/reverse-ptr.conf
- generated/dnsmasq/forwarding-mudpi.conf
- generated/dnsmasq/forwarding-shedpi.conf
- generated/dhcp/reid-reservations.conf
- generated/dhcp/barkingowl-reservations.conf
- generated/dhcp/trilogy-reservations.conf
- generated/dhcp/testboat-reservations.conf

Usage:
    python tools/generate-network-docs.py
    python tools/generate-network-docs.py --registry docs/reference/network-registry.yaml --output generated
"""

from __future__ import annotations

import argparse
import ipaddress
from pathlib import Path
from typing import Any, Dict, List, Tuple

import yaml


def load_registry(path: Path) -> Dict[str, Any]:
    with path.open("r", encoding="utf-8") as f:
        return yaml.safe_load(f)


def ensure_dir(path: Path) -> None:
    path.mkdir(parents=True, exist_ok=True)


def addr_sort_key(ip: str) -> Tuple[int, ...]:
    try:
        return tuple(int(part) for part in ip.split("."))
    except Exception:
        return (999, 999, 999, 999)


def fqdn(host: Dict[str, Any], registry: Dict[str, Any]) -> str:
    private_root = registry["meta"]["private_root"]
    return f'{host["name"]}.{host["site"]}.{private_root}'


def vpn_fqdn(host: Dict[str, Any], registry: Dict[str, Any]) -> str:
    private_root = registry["meta"]["private_root"]
    return f'{host["name"]}.vpn.{private_root}'


def host_records(host: Dict[str, Any], registry: Dict[str, Any]) -> List[Tuple[str, str]]:
    out: List[Tuple[str, str]] = []
    addresses = host.get("addresses", {})
    if "lan" in addresses:
        out.append((fqdn(host, registry), addresses["lan"]))
    if "vpn" in addresses:
        out.append((vpn_fqdn(host, registry), addresses["vpn"]))
    return out


def ptr_records(host: Dict[str, Any], registry: Dict[str, Any]) -> List[Tuple[str, str]]:
    return [(ip, name) for name, ip in host_records(host, registry)]


def markdown_table(headers: List[str], rows: List[List[str]]) -> str:
    if not rows:
        rows = [["—" for _ in headers]]
    lines = []
    lines.append("| " + " | ".join(headers) + " |")
    lines.append("| " + " | ".join(["---"] * len(headers)) + " |")
    for row in rows:
        safe = [("" if v is None else str(v)).replace("\n", "<br>") for v in row]
        lines.append("| " + " | ".join(safe) + " |")
    return "\n".join(lines)


def write_text(path: Path, content: str) -> None:
    path.write_text(content.rstrip() + "\n", encoding="utf-8")
    print(f"Wrote {path}")


def hosts_by_site(registry: Dict[str, Any]) -> Dict[str, List[Dict[str, Any]]]:
    grouped: Dict[str, List[Dict[str, Any]]] = {}
    for host in registry.get("hosts", []):
        grouped.setdefault(host["site"], []).append(host)
    for site_hosts in grouped.values():
        site_hosts.sort(
            key=lambda h: (
                addr_sort_key(h.get("addresses", {}).get("lan", "999.999.999.999")),
                h["name"],
            )
        )
    return grouped


def classify_host(host: Dict[str, Any]) -> str:
    roles = set(host.get("roles", []))
    name = host.get("name", "")

    if "gateway" in roles:
        return "gateway"
    if {"dns", "dhcp", "wireguard-hub", "ntp-stratum1"} & roles:
        return "critical-infrastructure"
    if {"app-host", "grafana", "influxdb", "signalk"} & roles:
        return "application"
    if {"weather", "sensor"} & roles:
        return "appliance"
    if "roaming-client" in roles or name in {"laptop", "phone", "tablet"}:
        return "client"
    return "general"


def generate_host_registry_md(registry: Dict[str, Any], out_path: Path) -> None:
    rows: List[List[str]] = []
    for host in sorted(registry.get("hosts", []), key=lambda h: (h["site"], h["name"])):
        addresses = host.get("addresses", {})
        roles = ", ".join(host.get("roles", []))
        rows.append([
            host["name"],
            host["site"],
            addresses.get("lan", "—"),
            addresses.get("vpn", "—"),
            host.get("addressing", "—"),
            roles or "—",
            host.get("notes", "—"),
        ])

    md = f"""# Host Registry

Generated from `docs/reference/network-registry.yaml`.

{markdown_table(
    ["Host", "Site", "LAN IP", "VPN IP", "Addressing", "Roles", "Notes"],
    rows,
)}
"""
    write_text(out_path, md)


def generate_site_summary_md(registry: Dict[str, Any], out_path: Path) -> None:
    sites = registry.get("sites", {})
    site_hosts = hosts_by_site(registry)

    parts = [
        "# Site Summary",
        "",
        "Generated from `docs/reference/network-registry.yaml`.",
        "",
    ]

    for site_name, site in sites.items():
        parts.append(f"## {site_name}")
        parts.append("")
        parts.append(f"**Zone:** `{site.get('zone', '—')}`  ")
        parts.append(f"**Description:** {site.get('description', '—')}  ")

        if "lan" in site:
            lan = site["lan"]
            parts.append(f"**LAN CIDR:** `{lan.get('cidr', '—')}`  ")
            parts.append(f"**Gateway:** `{lan.get('gateway', '—')}`  ")
        if "overlay" in site:
            overlay = site["overlay"]
            parts.append(f"**Overlay CIDR:** `{overlay.get('cidr', '—')}`  ")
            parts.append(f"**Hub:** `{overlay.get('hub', '—')}`  ")

        dns = site.get("dns", {})
        if dns:
            parts.append(f"**DNS mode:** `{dns.get('mode', '—')}`  ")
            if dns.get("server_host"):
                parts.append(f"**DNS server host:** `{dns['server_host']}`  ")
            if dns.get("server_ip"):
                parts.append(f"**DNS server IP:** `{dns['server_ip']}`  ")
            if dns.get("search_domain"):
                parts.append(f"**Search domain:** `{dns['search_domain']}`  ")

        dhcp = site.get("dhcp", {})
        if dhcp:
            parts.append(f"**DHCP mode:** `{dhcp.get('mode', '—')}`  ")
            if dhcp.get("authority"):
                parts.append(f"**DHCP authority:** `{dhcp['authority']}`  ")

        parts.append("")
        rows = []
        for host in site_hosts.get(site_name, []):
            addrs = host.get("addresses", {})
            rows.append([
                host["name"],
                addrs.get("lan", "—"),
                addrs.get("vpn", "—"),
                host.get("addressing", "—"),
                ", ".join(host.get("roles", [])) or "—",
            ])
        parts.append(markdown_table(
            ["Host", "LAN IP", "VPN IP", "Addressing", "Roles"],
            rows,
        ))
        parts.append("")

    write_text(out_path, "\n".join(parts))


def generate_dnsmasq_hosts(registry: Dict[str, Any], out_path: Path) -> None:
    records: List[Tuple[str, str]] = []
    for host in registry.get("hosts", []):
        records.extend(host_records(host, registry))

    records.sort(key=lambda item: (item[0], addr_sort_key(item[1])))

    lines = [
        "# Generated dnsmasq host records",
        "# Source: docs/reference/network-registry.yaml",
        "",
    ]
    for name, ip in records:
        lines.append(f"host-record={name},{ip}")

    write_text(out_path, "\n".join(lines))


def generate_dnsmasq_ptr(registry: Dict[str, Any], out_path: Path) -> None:
    records: List[Tuple[str, str]] = []
    for host in registry.get("hosts", []):
        records.extend(ptr_records(host, registry))

    records.sort(key=lambda item: addr_sort_key(item[0]))

    lines = [
        "# Generated dnsmasq PTR records",
        "# Source: docs/reference/network-registry.yaml",
        "",
    ]
    for ip, name in records:
        lines.append(f"ptr-record={ip},{name}")

    write_text(out_path, "\n".join(lines))


def generate_forwarding_conf(registry: Dict[str, Any], target: str, out_path: Path) -> None:
    forwarding = registry.get("forwarding", {}).get(target)
    if not forwarding:
        write_text(out_path, f"# No forwarding config found for {target}\n")
        return

    lines = [
        f"# Generated dnsmasq forwarding config for {target}",
        "# Source: docs/reference/network-registry.yaml",
        "",
    ]

    for zone in forwarding.get("authoritative_zones", []):
        lines.append(f"# authoritative: {zone}")

    conditional = forwarding.get("conditional_forwarders", {})
    if conditional:
        lines.append("")
        lines.append("# Conditional forwarders")
        for zone, server_ip in sorted(conditional.items()):
            lines.append(f"server=/{zone}/{server_ip}")

    upstream = forwarding.get("upstream_resolvers", [])
    if upstream:
        lines.append("")
        lines.append("# Upstream resolvers")
        for server_ip in upstream:
            lines.append(f"server={server_ip}")

    notes = forwarding.get("notes", [])
    if notes:
        lines.append("")
        lines.append("# Notes")
        for note in notes:
            lines.append(f"# - {note}")

    write_text(out_path, "\n".join(lines))


def generate_site_dhcp_reservations(registry: Dict[str, Any], site_name: str, out_path: Path) -> None:
    lines = [
        f"# Generated DHCP reservations for {site_name}",
        "# Source: docs/reference/network-registry.yaml",
        "",
    ]

    any_written = False
    for host in registry.get("hosts", []):
        if host.get("site") != site_name:
            continue
        if host.get("addressing") != "dhcp-reservation":
            continue

        mac = host.get("mac")
        ip = host.get("addresses", {}).get("lan")
        if not mac or str(mac).strip().upper() == "TBD" or not ip:
            lines.append(f"# Skipped {host['name']}: missing final MAC or LAN IP")
            continue

        lines.append(f"dhcp-host={mac},{host['name']},{ip}")
        any_written = True

    if not any_written:
        lines.append("# No completed DHCP reservations defined for this site yet")

    write_text(out_path, "\n".join(lines))


def generate_addressing_plan_md(registry: Dict[str, Any], out_path: Path) -> None:
    defaults = registry.get("defaults", {})
    conv = defaults.get("addressing_convention", {})
    dhcp_policy = defaults.get("dhcp_policy", {})
    sites = registry.get("sites", {})

    rows = [
        ["Gateway", f".{conv.get('gateway', '—')}"],
        ["Primary infrastructure node", f".{conv.get('infra_primary', '—')}"],
        ["Secondary / application host", f".{conv.get('app_secondary', '—')}"],
        ["Utility host", f".{conv.get('utility', '—')}"],
        ["Reserved appliances / sensors", f".{conv.get('reservations_start', '—')}–.{conv.get('reservations_end', '—')}"],
        ["Dynamic DHCP pool", f".{conv.get('dynamic_start', '—')}–.{conv.get('dynamic_end', '—')}"],
        ["Temporary / manual", f".{conv.get('temporary_start', '—')}–.{conv.get('temporary_end', '—')}"],
        ["Administrative reserve", f".{conv.get('admin_reserve_start', '—')}–.{conv.get('admin_reserve_end', '—')}"],
    ]

    policy_rows = [
        ["Infrastructure hosts", dhcp_policy.get("infrastructure", "—")],
        ["Appliances / sensors", dhcp_policy.get("appliances", "—")],
        ["Mobile clients", dhcp_policy.get("mobile_clients", "—")],
    ]

    parts = [
        "# Addressing Plan",
        "",
        "Generated from `docs/reference/network-registry.yaml`.",
        "",
        "## Standard host-role numbering",
        "",
        markdown_table(["Role", "Host ID"], rows),
        "",
        "## Address assignment policy",
        "",
        markdown_table(["Device Class", "Policy"], policy_rows),
        "",
        "## Site subnet summary",
        "",
    ]

    site_rows = []
    for site_name, site in sites.items():
        if "lan" in site:
            lan = site["lan"]
            site_rows.append([
                site_name,
                site.get("zone", "—"),
                lan.get("cidr", "—"),
                lan.get("gateway", "—"),
                site.get("dns", {}).get("server_ip", "—"),
                site.get("dhcp", {}).get("authority", "—"),
                site.get("dhcp", {}).get("search_domain", "—"),
            ])
        elif "overlay" in site:
            overlay = site["overlay"]
            site_rows.append([
                site_name,
                site.get("zone", "—"),
                overlay.get("cidr", "—"),
                overlay.get("hub", "—"),
                site.get("dns", {}).get("server_ip", "—"),
                "—",
                "—",
            ])

    parts.append(markdown_table(
        ["Site", "Zone", "CIDR", "Gateway/Hub", "DNS Server", "DHCP Authority", "Search Domain"],
        site_rows,
    ))
    parts.append("")

    write_text(out_path, "\n".join(parts))


def generate_network_inventory_md(registry: Dict[str, Any], out_path: Path) -> None:
    sites = registry.get("sites", {})
    grouped_hosts = hosts_by_site(registry)

    parts: List[str] = [
        "# Network Inventory",
        "",
        "Generated from `docs/reference/network-registry.yaml`.",
        "",
        "This document provides an operational inventory of the MudPi multi-site network,",
        "including sites, subnets, DNS/DHCP authority, key hosts, and service roles.",
        "It is intended as a human-readable engineering reference for maintenance,",
        "troubleshooting, and continuity of operations.",
        "",
        "## Estate Overview",
        "",
    ]

    overview_rows: List[List[str]] = []
    for site_name, site in sites.items():
        if "lan" in site:
            subnet = site["lan"].get("cidr", "—")
        else:
            subnet = site.get("overlay", {}).get("cidr", "—")
        overview_rows.append([
            site_name,
            site.get("zone", "—"),
            subnet,
            site.get("dns", {}).get("server_host", "—"),
            site.get("dhcp", {}).get("authority", "—"),
            site.get("description", "—"),
        ])
    parts.append(markdown_table(["Site", "Zone", "Subnet", "DNS", "DHCP", "Notes"], overview_rows))
    parts.append("")
    parts.append("## Critical Infrastructure Summary")
    parts.append("")

    critical_rows: List[List[str]] = []
    for host in sorted(registry.get("hosts", []), key=lambda h: (h["site"], h["name"])):
        if classify_host(host) != "critical-infrastructure":
            continue
        critical_rows.append([
            fqdn(host, registry),
            host.get("site", "—"),
            ", ".join(host.get("roles", [])) or "—",
            host.get("notes", "—"),
        ])

    parts.append(markdown_table(["Host", "Site", "Function", "Notes"], critical_rows))
    parts.append("")
    parts.append("## Addressing Policy Summary")
    parts.append("")

    defaults = registry.get("defaults", {})
    conv = defaults.get("addressing_convention", {})
    policy_rows = [
        ["Gateway", f".{conv.get('gateway', '—')}"],
        ["Primary infra node", f".{conv.get('infra_primary', '—')}"],
        ["Secondary / application host", f".{conv.get('app_secondary', '—')}"],
        ["Utility host", f".{conv.get('utility', '—')}"],
        ["Reserved appliances", f".{conv.get('reservations_start', '—')}–.{conv.get('reservations_end', '—')}"],
        ["Dynamic pool", f".{conv.get('dynamic_start', '—')}–.{conv.get('dynamic_end', '—')}"],
    ]
    parts.append(markdown_table(["Role", "Host ID"], policy_rows))
    parts.append("")

    for site_name, site in sites.items():
        parts.append(f"## Site Inventory: {site_name}")
        parts.append("")
        parts.append(f"**Zone:** `{site.get('zone', '—')}`  ")
        parts.append(f"**Description:** {site.get('description', '—')}  ")
        if "lan" in site:
            parts.append(f"**Subnet:** `{site['lan'].get('cidr', '—')}`  ")
            parts.append(f"**Gateway:** `{site['lan'].get('gateway', '—')}`  ")
        if "overlay" in site:
            parts.append(f"**Overlay:** `{site['overlay'].get('cidr', '—')}`  ")
            parts.append(f"**Hub:** `{site['overlay'].get('hub', '—')}`  ")
        if site.get("dns", {}).get("server_host"):
            parts.append(f"**DNS authority:** `{site['dns']['server_host']}`  ")
        if site.get("dhcp", {}).get("authority"):
            parts.append(f"**DHCP authority:** `{site['dhcp']['authority']}`  ")
        parts.append("")

        rows: List[List[str]] = []
        for host in grouped_hosts.get(site_name, []):
            addresses = host.get("addresses", {})
            rows.append([
                host["name"],
                fqdn(host, registry),
                addresses.get("lan", "—"),
                addresses.get("vpn", "—"),
                host.get("addressing", "—"),
                ", ".join(host.get("roles", [])) or "—",
                host.get("notes", "—"),
            ])
        parts.append(markdown_table(
            ["Host", "FQDN", "LAN IP", "VPN IP", "Addressing", "Roles", "Notes"],
            rows,
        ))
        parts.append("")

    parts.extend([
        "## Operational Notes",
        "",
        "- Infrastructure hosts use static addresses configured on-host where practical.",
        "- Appliances and sensors use DHCP reservations on the site DHCP server.",
        "- Mobile and visitor devices use dynamic DHCP pools.",
        "- Site-local short names depend on local DHCP search domains.",
        "- Canonical names follow the pattern `host.site.home.arpa`.",
        "- MudPi acts as the cross-site coordinating resolver for the estate.",
        "",
    ])

    write_text(out_path, "\n".join(parts))


def validate_registry(registry: Dict[str, Any]) -> List[str]:
    errors: List[str] = []

    site_names = set(registry.get("sites", {}).keys())
    seen_fqdns: set[str] = set()
    seen_ips: Dict[str, str] = {}

    for host in registry.get("hosts", []):
        site = host.get("site")
        if site not in site_names:
            errors.append(f"Host {host.get('name')} refers to unknown site {site!r}")

        for name, ip in host_records(host, registry):
            if name in seen_fqdns:
                errors.append(f"Duplicate FQDN detected: {name}")
            else:
                seen_fqdns.add(name)

            if ip in seen_ips:
                errors.append(f"IP address {ip} reused by {name} and {seen_ips[ip]}")
            else:
                seen_ips[ip] = name

            try:
                ipaddress.ip_address(ip)
            except ValueError:
                errors.append(f"Invalid IP address for {name}: {ip}")

    return errors


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate network docs and dnsmasq artifacts from YAML registry")
    parser.add_argument(
        "--registry",
        default="docs/reference/network-registry.yaml",
        help="Path to YAML registry (default: docs/reference/network-registry.yaml)",
    )
    parser.add_argument(
        "--output",
        default="generated",
        help="Output directory (default: generated)",
    )
    parser.add_argument(
        "--fail-on-validation",
        action="store_true",
        help="Exit non-zero if registry validation reports problems",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    registry_path = Path(args.registry)
    output_root = Path(args.output)

    registry = load_registry(registry_path)
    errors = validate_registry(registry)

    ensure_dir(output_root)
    ensure_dir(output_root / "dnsmasq")
    ensure_dir(output_root / "dhcp")

    generate_host_registry_md(registry, output_root / "host-registry.md")
    generate_site_summary_md(registry, output_root / "site-summary.md")
    generate_addressing_plan_md(registry, output_root / "addressing-plan.md")
    generate_network_inventory_md(registry, output_root / "network-inventory.md")

    generate_dnsmasq_hosts(registry, output_root / "dnsmasq" / "hosts.conf")
    generate_dnsmasq_ptr(registry, output_root / "dnsmasq" / "reverse-ptr.conf")
    generate_forwarding_conf(registry, "mudpi", output_root / "dnsmasq" / "forwarding-mudpi.conf")
    generate_forwarding_conf(registry, "shedpi", output_root / "dnsmasq" / "forwarding-shedpi.conf")

    for site_name in registry.get("sites", {}).keys():
        if site_name == "vpn":
            continue
        generate_site_dhcp_reservations(
            registry,
            site_name,
            output_root / "dhcp" / f"{site_name}-reservations.conf",
        )

    validation_md = [
        "# Registry Validation",
        "",
        f"Source registry: `{registry_path}`",
        "",
    ]
    if errors:
        validation_md.append("## Problems found")
        validation_md.append("")
        for err in errors:
            validation_md.append(f"- {err}")
    else:
        validation_md.append("No validation problems found.")
    write_text(output_root / "validation.md", "\n".join(validation_md))

    if errors:
        print("\nValidation reported issues:")
        for err in errors:
            print(f"  - {err}")
        if args.fail_on_validation:
            return 1

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
