#!/usr/bin/env python3
"""
generate_dnsmasq.py

Generate dnsmasq host, alias, and reverse-DNS config fragments from
network-registry.yaml.

Policy
------
- Every host with addresses.lan gets:
    * one canonical FQDN A record
    * one short-name A record (host name only)
    * one PTR record pointing back to the canonical FQDN
- If host.dns.canonical is present, use it.
- Otherwise derive the canonical FQDN as:
      {host.name}.{host.site}.{meta.private_root}
- Any host.dns.aliases entries become CNAMEs to the canonical FQDN.
- Hosts without addresses.lan are skipped for forward/reverse A/PTR output.
- Duplicate short names, canonical names, aliases, or LAN IPs are treated as errors.

Outputs
-------
The script writes three files into the chosen output directory:

    hosts.conf
    aliases.conf
    reverse.conf

Example
-------
    python3 tools/generate_dnsmasq.py docs/reference/network-registry.yaml
    python3 tools/generate_dnsmasq.py docs/reference/network-registry.yaml --output generated/dns

Deployment example
------------------
    sudo cp generated/dns/*.conf /etc/dnsmasq.d/
    sudo systemctl restart dnsmasq
"""

from __future__ import annotations

import argparse
import ipaddress
import re
import sys
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional, Set, Tuple

import yaml


FQDN_RE = re.compile(r"^(?=.{1,253}$)(?!-)[A-Za-z0-9-]+(\.(?!-)[A-Za-z0-9-]+)+\.?$")
HOST_RE = re.compile(r"^[a-z0-9](?:[a-z0-9-]*[a-z0-9])?$")


class GenerationError(Exception):
    pass


def load_yaml(path: Path) -> Dict[str, Any]:
    try:
        with path.open("r", encoding="utf-8") as fh:
            data = yaml.safe_load(fh)
    except FileNotFoundError as exc:
        raise GenerationError(f"file not found: {path}") from exc
    except yaml.YAMLError as exc:
        raise GenerationError(f"YAML parse error in {path}: {exc}") from exc

    if not isinstance(data, dict):
        raise GenerationError("top-level YAML document must be a mapping")

    return data


def is_fqdn(value: Any) -> bool:
    return isinstance(value, str) and bool(FQDN_RE.match(value))


def normalize_fqdn(value: str) -> str:
    return value.rstrip(".").lower()


def derive_canonical_fqdn(host: Dict[str, Any], private_root: str) -> str:
    name = host.get("name")
    site = host.get("site")
    if not isinstance(name, str) or not isinstance(site, str):
        raise GenerationError("host missing name or site for canonical FQDN derivation")
    return f"{name}.{site}.{private_root}".lower()


def get_canonical_fqdn(host: Dict[str, Any], private_root: str) -> str:
    dns = host.get("dns", {})
    if isinstance(dns, dict):
        canonical = dns.get("canonical")
        if canonical:
            if not is_fqdn(canonical):
                raise GenerationError(
                    f"host {host.get('name', '<unnamed>')}: invalid dns.canonical {canonical!r}"
                )
            return normalize_fqdn(canonical)
    return derive_canonical_fqdn(host, private_root)


def get_dns_aliases(host: Dict[str, Any]) -> List[str]:
    dns = host.get("dns", {})
    if not isinstance(dns, dict):
        return []
    aliases = dns.get("aliases", [])
    if aliases is None:
        return []
    if not isinstance(aliases, list):
        raise GenerationError(
            f"host {host.get('name', '<unnamed>')}: dns.aliases must be a list"
        )

    result: List[str] = []
    seen: Set[str] = set()
    for alias in aliases:
        if not isinstance(alias, str):
            raise GenerationError(
                f"host {host.get('name', '<unnamed>')}: dns.aliases contains non-string value"
            )
        if not is_fqdn(alias):
            raise GenerationError(
                f"host {host.get('name', '<unnamed>')}: invalid alias FQDN {alias!r}"
            )
        key = normalize_fqdn(alias)
        if key not in seen:
            seen.add(key)
            result.append(key)
    return result


def get_lan_ip(host: Dict[str, Any]) -> Optional[str]:
    addresses = host.get("addresses", {})
    if not isinstance(addresses, dict):
        return None
    lan = addresses.get("lan")
    if lan is None:
        return None
    if not isinstance(lan, str):
        raise GenerationError(
            f"host {host.get('name', '<unnamed>')}: addresses.lan must be a string"
        )
    try:
        ipaddress.IPv4Address(lan)
    except ValueError as exc:
        raise GenerationError(
            f"host {host.get('name', '<unnamed>')}: invalid addresses.lan {lan!r}"
        ) from exc
    return lan


def reverse_name_for_ipv4(ip: str) -> str:
    addr = ipaddress.IPv4Address(ip)
    octets = str(addr).split(".")
    return ".".join(reversed(octets)) + ".in-addr.arpa"


def emit_header(title: str) -> str:
    return (
        f"# ------------------------------------------------------------------\n"
        f"# {title}\n"
        f"# Generated by generate_dnsmasq.py. Do not edit by hand.\n"
        f"# ------------------------------------------------------------------\n"
    )


def generate_fragments(registry: Dict[str, Any]) -> Tuple[List[str], List[str], List[str]]:
    private_root = registry.get("meta", {}).get("private_root", "home.arpa")
    if not isinstance(private_root, str):
        raise GenerationError("meta.private_root must be a string")

    hosts = registry.get("hosts", [])
    if not isinstance(hosts, list):
        raise GenerationError("hosts must be a list")

    host_lines: List[str] = []
    alias_lines: List[str] = []
    reverse_lines: List[str] = []

    seen_short_names: Dict[str, str] = {}
    seen_fqdns: Dict[str, str] = {}
    seen_ips: Dict[str, str] = {}

    for idx, host in enumerate(hosts):
        if not isinstance(host, dict):
            raise GenerationError(f"hosts[{idx}] must be a mapping")

        name = host.get("name")
        if not isinstance(name, str) or not HOST_RE.match(name):
            raise GenerationError(f"hosts[{idx}].name must be a valid short hostname label")

        lan_ip = get_lan_ip(host)
        if lan_ip is None:
            continue

        canonical = get_canonical_fqdn(host, private_root)
        aliases = get_dns_aliases(host)

        if name in seen_short_names:
            raise GenerationError(
                f"duplicate short host name {name!r}; already used by {seen_short_names[name]!r}"
            )
        seen_short_names[name] = name

        if canonical in seen_fqdns:
            raise GenerationError(
                f"duplicate canonical/alias FQDN {canonical!r}; already used by {seen_fqdns[canonical]!r}"
            )
        seen_fqdns[canonical] = name

        for alias in aliases:
            if alias in seen_fqdns:
                raise GenerationError(
                    f"duplicate canonical/alias FQDN {alias!r}; already used by {seen_fqdns[alias]!r}"
                )
            seen_fqdns[alias] = name

        if lan_ip in seen_ips:
            raise GenerationError(
                f"duplicate LAN IP {lan_ip!r}; already used by {seen_ips[lan_ip]!r}"
            )
        seen_ips[lan_ip] = name

        host_lines.append(f"host-record={canonical},{lan_ip}")
        host_lines.append(f"host-record={name},{lan_ip}")

        for alias in aliases:
            alias_lines.append(f"cname={alias},{canonical}")

        reverse_lines.append(f"ptr-record={reverse_name_for_ipv4(lan_ip)},{canonical}")

    host_lines.sort()
    alias_lines.sort()
    reverse_lines.sort()

    return host_lines, alias_lines, reverse_lines


def write_fragment(path: Path, title: str, lines: Iterable[str]) -> None:
    content = emit_header(title)
    body = "\n".join(lines)
    if body:
        content += body + "\n"
    path.write_text(content, encoding="utf-8")


def main(argv: Optional[List[str]] = None) -> int:
    parser = argparse.ArgumentParser(description="Generate dnsmasq config fragments from network-registry.yaml")
    parser.add_argument("yaml_file", help="Path to network-registry.yaml")
    parser.add_argument(
        "--output",
        default="generated/dns",
        help="Output directory for generated dnsmasq fragments (default: generated/dns)",
    )
    args = parser.parse_args(argv)

    try:
        registry = load_yaml(Path(args.yaml_file))
        host_lines, alias_lines, reverse_lines = generate_fragments(registry)
    except GenerationError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1

    out_dir = Path(args.output)
    out_dir.mkdir(parents=True, exist_ok=True)

    write_fragment(out_dir / "10-hosts.conf", "Forward host records", host_lines)
    write_fragment(out_dir / "20-aliases.conf", "DNS aliases", alias_lines)
    write_fragment(out_dir / "30-reverse.conf", "Reverse DNS PTR records", reverse_lines)

    print(f"Wrote {out_dir / '10-hosts.conf'}")
    print(f"Wrote {out_dir / '20-aliases.conf'}")
    print(f"Wrote {out_dir / '30-reverse.conf'}")
    print()
    print(f"Summary: {len(host_lines)} host record(s), {len(alias_lines)} alias record(s), {len(reverse_lines)} PTR record(s)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

