[Interface]
Address = 10.8.1.1/24
ListenPort = 51820
PrivateKey = OKMeDUVmP47KdUqFrN5UdaXOChqIpFs2NacwVRpNb0M=

# shedpi
[Peer]
PublicKey = /QRwyEw2IlZBFgOMY1LzIicE6/XFIgDYQMdarsoMUj0=
AllowedIPs = 10.8.1.20/32, 192.168.0.0/24

# sten-laptop
[Peer]
PublicKey = lOvUrzOhA5Y6zzawJUkhV/DXPFOA6XyQrVzTw8jqswk=
AllowedIPs = 10.8.1.101/32

# sten-phone
[Peer]
PublicKey = RvVzIpsWHcX/ub5t/jiCn0+/A/0arOxq+fesV85eUiA=
PresharedKey = jidRpilbC2TuJMfgM8UPgcWUBXooLc8zL1sfqOPG838=
AllowedIPs = 10.8.1.102/32

# james-laptop
[Peer]
PublicKey = 4f9haVVChuZKcejlIrYWOkuAAZbmcO9DtOPGPeoC1Dk=
PresharedKey = CjgAxdET2RMI1cePfTxEydewwcQ1sxT2/yLNuZPHgIA=
AllowedIPs = 10.8.1.110/32

# irene-iphone
[Peer]
PublicKey = ZHVTCq8m5LtSttny4RM0AkKr0ZVMhkNVGKCIqlId10Q=
PresharedKey = JThNIjWoys/cbwAMkMHqomB6ggksKVrNCaEklL/B7dw=
AllowedIPs = 10.8.1.120/32
